version: "3.9"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    networks:
    - bitcoin_exchanger

  backend:
    tty: true
    stdin_open: true
    build: ./
    entrypoint: "/app/entrypoint.sh"
    command: make
    volumes:
      - myapp:/app
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    networks:
      - bitcoin_exchanger
    depends_on:
      - redis

volumes:
  myapp:

networks:
  bitcoin_exchanger:
    driver: bridge
